export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_MEASUREMENTS = 'SET_MEASUREMENTS';
export const CREATE_MEASUREMENT = 'CREATE_MEASUREMENT';
export const FETCH_MEASUREDS_REQUEST = 'FETCH_MEASUREDS_REQUEST';
export const FETCH_MEASUREDS_SUCCESS = 'FETCH_MEASUREDS_SUCCESS';
export const FETCH_MEASUREDS_FAILURE = 'FETCH_MEASUREDS_FAILURE';
